// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKvGcIVzVVZi0L3ZzV_prCYkuS87wWD8',
    appId: '1:824098632084:web:99a05fb769329ef0091f81',
    messagingSenderId: '824098632084',
    projectId: 'tfg-ma',
    authDomain: 'tfg-ma.firebaseapp.com',
    storageBucket: 'tfg-ma.appspot.com',
    measurementId: 'G-RN8SEVBYKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SFa08Ne8acIAWRyiMxVrAop_b_pdM0Q',
    appId: '1:824098632084:android:e8122c69341316ae091f81',
    messagingSenderId: '824098632084',
    projectId: 'tfg-ma',
    storageBucket: 'tfg-ma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFbY0YCffAU2d5y7L8ycM-UU6tOMxi1g',
    appId: '1:824098632084:ios:dc1ce137dc194b75091f81',
    messagingSenderId: '824098632084',
    projectId: 'tfg-ma',
    storageBucket: 'tfg-ma.appspot.com',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRFbY0YCffAU2d5y7L8ycM-UU6tOMxi1g',
    appId: '1:824098632084:ios:dc1ce137dc194b75091f81',
    messagingSenderId: '824098632084',
    projectId: 'tfg-ma',
    storageBucket: 'tfg-ma.appspot.com',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOKvGcIVzVVZi0L3ZzV_prCYkuS87wWD8',
    appId: '1:824098632084:web:979cc4c255bd2dba091f81',
    messagingSenderId: '824098632084',
    projectId: 'tfg-ma',
    authDomain: 'tfg-ma.firebaseapp.com',
    storageBucket: 'tfg-ma.appspot.com',
    measurementId: 'G-BGYT1CRG2B',
  );

}